###
GET http://localhost:8080/v1/datasources
Content-Type: application/json
Accept: application/json

###
GET http://localhost:8080/v1/datasources/cf8669df-b559-4dfc-b23c-c2fe0a511560
Content-Type: application/json
Accept: application/json

###
POST http://localhost:8080/v1/datasources
Content-Type: application/json
Accept: application/json

{
  "host": "localhost",
  "database": "db-test",
  "port": 5432,
  "username": "postgres",
  "password": "root",
  "ssl_mode": "disable",
  "cron": {
    "cron_expr": "0 27 15 * * *",
    "description": "Executar a cada 1 segundo",
    "enabled": false
  }
}

###
PUT http://localhost:8080/v1/datasources/c92b0330-363e-436c-9bea-c99aa4ba6bfb
Content-Type: application/json
Accept: application/json

{
  "host": "localhost",
  "database": "teste-restore",
  "port": 5432,
  "username": "postgres",
  "password": "root",
  "ssl_mode": "disable",
  "cron": {
    "cron_expr": "0 27 15 * * *",
    "description": "Executar a cada 1 segundo",
    "enabled": true
  }
}


###
DELETE  http://localhost:8080/v1/datasources/6b558856-ef22-4459-a84a-9c1d0d3c13d7
Content-Type: application/json
Accept: application/json
