###
GET http://localhost:8080/v1/datasources
Content-Type: application/json
Accept: application/json

###
GET http://localhost:8080/v1/datasources/6aed1767-af62-4601-bf6c-5db9f6e74104
Content-Type: application/json
Accept: application/json



###
POST http://localhost:8080/v1/datasources
Content-Type: application/json
Accept: application/json

{
  "host": "localhost",
  "database": "fincycle",
  "port": 5432,
  "username": "postgres",
  "password": "root",
  "ssl_mode": "disable",
  "cron": {
    "cron_expr": "0 */5 * * * *",
    "description": "Executar a cada 5 minutos",
    "enabled": true
  }
}



###
PUT http://localhost:8080/v1/datasources/6aed1767-af62-4601-bf6c-5db9f6e74104
Content-Type: application/json
Accept: application/json

{
  "host": "localhost",
    "database": "fincycle",
    "port": 5432,
    "username": "postgres",
    "ssl_mode": "disable",
    "password": "root",
    "cron": {
      "cron_expr": "0 0 20 * * *",
      "description": "Executar a cada 5 minutos",
      "enabled": true
    }
}


###
DELETE  http://localhost:8080/v1/datasources/6b558856-ef22-4459-a84a-9c1d0d3c13d7
Content-Type: application/json
Accept: application/json
